//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiMus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ride
    {
        public int ID { get; set; }
        public string PickUpAddress { get; set; }
        public string DropAddress { get; set; }
        public double Price { get; set; }
        public string Status { get; set; }
        public byte PaymentStatus { get; set; }
        public double Distance { get; set; }
        public System.TimeSpan TripTime { get; set; }
        public System.TimeSpan WaitTime { get; set; }
        public Nullable<double> Rating { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> DriverID { get; set; }
        public Nullable<int> VehicleID { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual User User { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
